### ISSUE TITLE
TreeView: Unable to copy text from table

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#70]
Text cannot be selected and copied from the table. Tested in Firefox and Edge.

**Comment by paveljanda** [comment]
It works for me in latest Firefox, Chrome and Safari on Mac. I will test that on Windows.

**Comment by juniwalk** [comment]
I checked the examples in documentation and it works for me too, looks like it is something on my end, strange.

**Comment by paveljanda** [comment]
There are some styles and scripts, for example:

```css
.col-checkbox {
	-webkit-touch-callout: none;
	-webkit-user-select: none;
	-khtml-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
}
```

But that should only offect the checkbox inputs, not other row columns.
